parameters:
    oro_datagrid.importexport.export_connector.class:   Oro\Bundle\DataGridBundle\ImportExport\DatagridExportConnector

services:
    oro_datagrid.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        tags:
            - { name: oro_importexport.processor, type: export, entity: datagrid, alias: oro_datagrid }

    oro_datagrid.importexport.export_connector:
        class: %oro_datagrid.importexport.export_connector.class%
        arguments:
            - @oro_datagrid.datagrid.manager
            - @oro_importexport.context_registry
            - @doctrine
