parameters:
    oro_grid.datagrid.base.class: Oro\Bundle\DataGridBundle\Datagrid\Datagrid

    oro_grid.datagrid.manager.class: Oro\Bundle\DataGridBundle\Datagrid\Manager
    oro_grid.datagrid.builder.class: Oro\Bundle\DataGridBundle\Datagrid\Builder

services:
    oro_grid.datagrid.manager:
        class: %oro_grid.datagrid.manager.class%
        arguments:
            - []
            - @oro_grid.datagrid.builder

    oro_grid.datagrid.builder:
        class: %oro_grid.datagrid.builder.class%
        arguments:
            - %oro_grid.datagrid.base.class%

    oro_email.grid.query_builder:
        class: Oro\Bundle\EmailBundle\Provider\QueryBuilder
