elements:
  Grid:
    selector: 'div.grid-container'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\Grid

  GridHeader:
    selector: '.grid-header:nth-child(1)'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\GridHeader

  GridRow:
    selector: 'tbody tr'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element

  GridHeaderLink:
    selector: 'th a'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element

  GridFilters:
    selector: 'div.filter-box'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\GridFilters

  GridFilersButton:
    selector: 'div.toolbar div.actions-panel .action[title=Filters]'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\GridFiltersButton

  GridFilterStringItem:
    selector: 'div.filter-item'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\GridFilterStringItem

  GridFilterDateTimeItem:
    selector: 'div.filter-item'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\GridFilterDateTimeItem

  MultipleChoice:
    selector: 'div.filter-item'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\MultipleChoice

  DateTimePicker:
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\DateTimePicker

  GridPaginator:
    selector: 'div.toolbar div.pagination'
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\GridPaginator

  GridToolbarActions:
      selector: 'div.toolbar div.actions-panel'
      class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\GridToolbarActions

  GridFloatingMenu:
    selector: '.dropdown-menu__floating'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element

  MassActionHeadCheckbox:
    selector: 'div.grid-container th.grid-header-cell-massAction div.btn-group .btn'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element

  PageSize:
    selector: 'div.page-size'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element

  Modal:
    selector: 'div.modal'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element
