styles:
    inputs:
        - 'bundles/bowerassets/backgrid/lib/backgrid.css'
        - 'bundles/bowerassets/backgrid-paginator/backgrid-paginator.css'
        - 'bundles/orodatagrid/css/less/main.less'
